use: [Function: use],
    handle: [Function: handle],
    listen: [Function: listen],
    domain: undefined,
    _events: undefined,
    _maxListeners: undefined,
    setMaxListeners: [Function: setMaxListeners],
    getMaxListeners: [Function: getMaxListeners],
    emit: [Function: emit],
    addListener: [Function: addListener],
    on: [Function: addListener],
    prependListener: [Function: prependListener],
    once: [Function: once],
    prependOnceListener: [Function: prependOnceListener],
    removeListener: [Function: removeListener],
    removeAllListeners: [Function: removeAllListeners],
    listeners: [Function: listeners],
    listenerCount: [Function: listenerCount],
    eventNames: [Function: eventNames],
    route: '/',
    stack: [{ route: '', handle: [Function: compression] },
        { route: '', handle: [Function: _cookieSession] },
        { route: '', handle: [Function: urlencodedParser] },
        { route: '', handle: [Function] },
        { route: '', handle: [Function: middleware1] },
        { route: '', handle: [Function: middleware2] },
        { route: '', handle: [Function] },
        { route: '/foo', handle: [Function: fooMiddleware] },
        { route: '/bar', handle: [Function: barMiddleware] },
        { route: '', handle: [Function] },
        { route: '', handle: [Function: onerror] }
    ]
}